In [11]:
#Numpyの読み込み
import numpy as np

#2つの行列を格納する多次元配列のコードを記入
A = np.array([[0,1], [2,3], [4,5]])
B = np.array([[0,1,2,3], [4,5,6,7]])

#2つの行列の積を計算
np.dot(A, B)

#計算結果を表示するコードを記入
print(f'2つの行列の積、計算結果は以下になります。\n{np.dot(A,B)}\n')

#行列の要素の最大値を求めるコードを記入
a = np.dot(A, B)
np.max(a)
print(f'最大値は{np.max(a)}です。')

2つの行列の積、計算結果は以下になります。
[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]

最大値は47です。
